on:
  push:
    branches:
    - master_tests
name: master Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install Singularity
      run: |
       bash .github/scripts/install_singularity.sh
    - name: Build pipeline Singularity containers
      run: |
       echo $(which singularity)
       bash scripts/build_singularity_containers.sh
    - name: install Conda
      run: bash .github/scripts/install_conda.sh
    - name: install Nextflow via Conda
      run: |
       export PATH=/opt/conda/bin:$PATH
       conda install -c bioconda nextflow
       NXF_VER=20.03.0-edge nextflow -version
    - name: test PR outputs against previous release
      run: bash .github/scripts/test_PR_against_release.sh
    - name: test -profile sanger
      run: bash .github/scripts/test_sanger_profile.sh
    - name: test --cache conda environment 
      run: bash .github/scripts/test_conda_cache.sh
    - name: test --bed and --ref input options 
      run: bash .github/scripts/test_bed_ref_input.sh
    - name: test --cram input together with --bed and --ref
    - name: add log to artifacts
      if: failure()
      run: mv .nextflow.log artifacts/failure.nextflow.log
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test_artifacts
        path: artifacts