on:
  push:
    branches:
    - tests
name: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      uses: skx/github-action-tester@master
      container: docker://continuumio/miniconda3:latest
      with:
        script: .github/run_develop_tests.sh
    - run: mkdir -p artifacts
    - run: echo test finished >> artifacts/test_artifact.log
    - uses: actions/upload-artifact@v1
      with:
        name: test_artifacts
        path: artifacts