on:
  push:
    branches:
    - tests
name: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: continuumio/miniconda3:latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      uses: skx/github-action-tester@master
      with:
        script: .github/run_develop_tests.sh