on:
  push:
    branches:
    - tests
name: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build singularity containers
      run: |
       bash .github/install_singularity.sh
       bash scripts/build_singularity_containers.sh
    - name: Run tests
      uses: skx/github-action-tester@master
      with:
        script: .github/run_develop_tests.sh
    - uses: actions/upload-artifact@v1
      with:
        name: test_artifacts
        path: artifacts