on:
  push:
    branches:
    - tests
name: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install go compiler
      run: |
       source .github/install_go.sh
       ls -ltra /usr/local/
    - name: install Singularity
      run: |
       bash .github/install_singularity.sh
    - name: install Conda
      run: bash .github/install_conda.sh
    - name: install Nextflow via Conda
      run: |
       export PATH=/opt/conda/bin:$PATH
       conda install -c bioconda nextflow
       NXF_VER=20.03.0-edge nextflow -version
    - name: Build pipeline Singularity containers
      run: |
       echo $(which singularity)
       bash scripts/build_singularity_containers.sh
    - name: Run tests
      run: |
       echo $(which singularity)
       bash .github/run_develop_tests.sh
    - uses: actions/upload-artifact@v1
      with:
        name: test_artifacts
        path: artifacts