on:
  push:
    branches:
    - tests
name: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: continuumio/miniconda3:latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      uses: skx/github-action-tester@master
      with:
        script: .github/run_develop_tests.sh
    - run: mkdir -p artifacts
    - run: echo test run >> artifacts/test_artifact.txt
    - uses: actions/upload-artifact@v1
      with:
        name: test_artifact
        path: artifacts/test_artifact.txt